variable "create" {
  description = "Create the security group and its rules. When false the module creates nothing and outputs null identifiers."
  type        = bool
  default     = true
  nullable    = false
}

variable "name" {
  description = "Security group name. Must be unique within the VPC. Also the group's Name tag. When create_before_destroy_group is true the group's name is instead generated by AWS from name_prefix = \"<name>-\" plus a unique suffix, so name must then be at most 228 characters."
  type        = string
  nullable    = false

  validation {
    condition     = length(var.name) >= 1 && length(var.name) <= 255 && !startswith(var.name, "sg-")
    error_message = "name must be 1-255 characters and must not start with sg-."
  }
}

variable "description" {
  description = "Security group description. Changing it replaces the group."
  type        = string
  default     = "ECS task security group"
  nullable    = false
}

variable "vpc_id" {
  description = "VPC the security group belongs to. Required when create is true."
  type        = string
  default     = null
}

variable "ingress_rules" {
  description = "Ingress rules keyed by a stable identifier. Each rule names exactly one source: cidr_ipv4, cidr_ipv6, prefix_list_id, referenced_security_group_id, or self."
  type = map(object({
    description                  = optional(string)
    from_port                    = optional(number)
    to_port                      = optional(number)
    ip_protocol                  = optional(string, "tcp")
    cidr_ipv4                    = optional(string)
    cidr_ipv6                    = optional(string)
    prefix_list_id               = optional(string)
    referenced_security_group_id = optional(string)
    self                         = optional(bool, false)
  }))
  default  = {}
  nullable = false

  validation {
    condition = alltrue([for rule in values(var.ingress_rules) :
      length([for source in [rule.cidr_ipv4, rule.cidr_ipv6, rule.prefix_list_id, rule.referenced_security_group_id] : source if source != null]) + (rule.self ? 1 : 0) == 1
    ])
    error_message = "Each ingress rule must declare exactly one source: cidr_ipv4, cidr_ipv6, prefix_list_id, referenced_security_group_id, or self."
  }

  validation {
    condition = alltrue([for rule in values(var.ingress_rules) :
      contains(["tcp", "udp", "icmp", "icmpv6", "-1"], lower(rule.ip_protocol)) ? true : (
        can(regex("^[0-9]{1,3}$", rule.ip_protocol)) ? tonumber(rule.ip_protocol) <= 255 : false
      )
    ])
    error_message = "Ingress rule ip_protocol must be tcp, udp, icmp, icmpv6, -1 (all protocols), or an IP protocol number from 0 to 255."
  }

  # Ports by protocol family. tcp/udp (6/17): from_port and to_port are
  # required, -1 to 65535, from_port <= to_port. icmp/icmpv6 (1/58): from_port
  # is the ICMP type and to_port the ICMP code, both required and each -1 to
  # 255, with no ordering between them (type 8 code 0 is valid). -1: no ports.
  # Any other protocol number (for example 50, ESP): AWS ignores ports, so
  # both may be omitted; if set they must satisfy the tcp/udp rule, as in
  # 1.1.0. Nested conditionals because Terraform 1.7 does not short-circuit.
  validation {
    condition = alltrue([for rule in values(var.ingress_rules) :
      rule.ip_protocol == "-1" ? (rule.from_port == null && rule.to_port == null) : (
        contains(["icmp", "icmpv6", "1", "58"], lower(rule.ip_protocol)) ? (
          (rule.from_port == null || rule.to_port == null) ? false : (rule.from_port >= -1 && rule.from_port <= 255 && rule.to_port >= -1 && rule.to_port <= 255)
          ) : (
          !contains(["tcp", "udp", "6", "17"], lower(rule.ip_protocol)) && rule.from_port == null && rule.to_port == null ? true : (
            (rule.from_port == null || rule.to_port == null) ? false : (rule.from_port >= -1 && rule.to_port <= 65535 && rule.from_port <= rule.to_port)
          )
        )
      )
    ])
    error_message = "Ingress rules need from_port and to_port for tcp/udp (-1 to 65535, from_port <= to_port) and for icmp/icmpv6 (ICMP type and code, each -1 to 255); all-protocol (-1) rules must not set ports; other protocol numbers may omit both."
  }
}

variable "egress_rules" {
  description = "Egress rules keyed by a stable identifier, same shape as ingress_rules. A group with no egress rules cannot pull images or reach any dependency."
  type = map(object({
    description                  = optional(string)
    from_port                    = optional(number)
    to_port                      = optional(number)
    ip_protocol                  = optional(string, "tcp")
    cidr_ipv4                    = optional(string)
    cidr_ipv6                    = optional(string)
    prefix_list_id               = optional(string)
    referenced_security_group_id = optional(string)
    self                         = optional(bool, false)
  }))
  default  = {}
  nullable = false

  validation {
    condition = alltrue([for rule in values(var.egress_rules) :
      length([for source in [rule.cidr_ipv4, rule.cidr_ipv6, rule.prefix_list_id, rule.referenced_security_group_id] : source if source != null]) + (rule.self ? 1 : 0) == 1
    ])
    error_message = "Each egress rule must declare exactly one destination: cidr_ipv4, cidr_ipv6, prefix_list_id, referenced_security_group_id, or self."
  }

  validation {
    condition = alltrue([for rule in values(var.egress_rules) :
      contains(["tcp", "udp", "icmp", "icmpv6", "-1"], lower(rule.ip_protocol)) ? true : (
        can(regex("^[0-9]{1,3}$", rule.ip_protocol)) ? tonumber(rule.ip_protocol) <= 255 : false
      )
    ])
    error_message = "Egress rule ip_protocol must be tcp, udp, icmp, icmpv6, -1 (all protocols), or an IP protocol number from 0 to 255."
  }

  # Ports by protocol family. tcp/udp (6/17): from_port and to_port are
  # required, -1 to 65535, from_port <= to_port. icmp/icmpv6 (1/58): from_port
  # is the ICMP type and to_port the ICMP code, both required and each -1 to
  # 255, with no ordering between them (type 8 code 0 is valid). -1: no ports.
  # Any other protocol number (for example 50, ESP): AWS ignores ports, so
  # both may be omitted; if set they must satisfy the tcp/udp rule, as in
  # 1.1.0. Nested conditionals because Terraform 1.7 does not short-circuit.
  validation {
    condition = alltrue([for rule in values(var.egress_rules) :
      rule.ip_protocol == "-1" ? (rule.from_port == null && rule.to_port == null) : (
        contains(["icmp", "icmpv6", "1", "58"], lower(rule.ip_protocol)) ? (
          (rule.from_port == null || rule.to_port == null) ? false : (rule.from_port >= -1 && rule.from_port <= 255 && rule.to_port >= -1 && rule.to_port <= 255)
          ) : (
          !contains(["tcp", "udp", "6", "17"], lower(rule.ip_protocol)) && rule.from_port == null && rule.to_port == null ? true : (
            (rule.from_port == null || rule.to_port == null) ? false : (rule.from_port >= -1 && rule.to_port <= 65535 && rule.from_port <= rule.to_port)
          )
        )
      )
    ])
    error_message = "Egress rules need from_port and to_port for tcp/udp (-1 to 65535, from_port <= to_port) and for icmp/icmpv6 (ICMP type and code, each -1 to 255); all-protocol (-1) rules must not set ports; other protocol numbers may omit both."
  }
}

variable "tags" {
  description = "Tags applied to the security group and every rule. Keys must not use the AWS-reserved aws: prefix."
  type        = map(string)
  default     = {}
  nullable    = false

  validation {
    condition     = alltrue([for key in keys(var.tags) : !startswith(lower(key), "aws:")])
    error_message = "Tag keys must not start with the reserved prefix aws: (in any letter case)."
  }
}

variable "create_before_destroy_group" {
  description = "When true, the security group is managed by aws_security_group.this_cbd, which has lifecycle.create_before_destroy and is named by AWS from name_prefix = \"<name>-\" plus a unique suffix (the Name tag stays name). A forced replacement (for example a description change, which is immutable on aws_security_group) then creates the new group, under a new unique name, before destroying the old one, so there is no window without a security group. Default false keeps the original resource, aws_security_group.this, with the fixed name = name. Flipping this on an existing group switches which of the two resources manages it. A caller-side moved block between module.<call>.aws_security_group.this[0] and module.<call>.aws_security_group.this_cbd[0] carries the state across, but the group is still replaced once because the two variants name it differently (fixed name versus name_prefix): create-before-destroy when turning it on, destroy-then-create when turning it off. Without a moved block Terraform destroys one resource and creates the other with no ordering guarantee between them. Neither direction collides on the group name, since exactly one side always uses a generated name. Set it once, at adoption, not as an ongoing toggle."
  type        = bool
  default     = false
  nullable    = false
}
